dataset_name: bodycam
train_split: ['train']
val_split: ['test']
dataset: {
  json_file: ./data/InternVideo_Police_BWC_Car_v3.json,
  feat_folder: /scratch/slee67/bodycam_mp4,
  file_prefix: ~,
  file_ext: .mp4,
  num_classes: 1,
  input_dim: 2000,                  #2048+768, 1024+768,1280+1024, 1280+720??
  feat_stride: 4,                   # Defines how many frames to shift the attention window at a time
  num_frames: 16,                   # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 65536,               # Is this the frames in the longest video. OLD: 2304
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,       # max buffer size (defined a factor of max_seq_len)
  n_mha_win_size: 16,               # window size for self attention; -1 to use full seq
}
opt: {
  learning_rate: 0.0001,
  epochs: 45,
  weight_decay: 0.05,
}
loader: {
  batch_size: 1,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
# the inference on THUMOS is quite different from EPIC-kitchens
# a major performance gain is achieved by fusing external classification scores
# doing so will require disable multiclass_nms and enable score fusion
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: ./ckpt_bwc/
